stages:
  - init
  - validate
  - plan
  - apply
  - destroy

image:
  name: hashicorp/terraform:latest
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'


before_script:
  - apk add --no-cache aws-cli curl unzip bash
  - aws --version
  - terraform --version

init:
  stage: init
  script:
    - terraform init
  artifacts:
    paths:
      - .terraform/
      - .terraform.lock.hcl

validate:
  stage: validate
  dependencies:
    - init
  script:
    - terraform validate

plan:
  stage: plan
  dependencies:
    - init
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan
      - terraform.tfstate
      - .terraform/
      - .terraform.lock.hcl
  only:
    - main

apply:
  stage: apply
  dependencies:
    - plan
  script:
    - terraform apply -auto-approve tfplan
  artifacts:
    paths:
      - terraform.tfstate
  only:
    - main

destroy:
  stage: destroy
  dependencies:
    - apply  # Get updated tfstate after apply
  script:
    - terraform init
    - terraform destroy -auto-approve
  when: manual
  only:
    - main
